plugins:
  isthereanydeal_enabled:
    default: false
    type: bool

  isthereanydeal_api_key:
    default: ""
    secret: true

  isthereanydeal_category_id:
    default: ""
    type: category

  isthereanydeal_country:
    default: "EU"
    type: string

  isthereanydeal_include_dlc:
    default: false
    type: bool

  isthereanydeal_include_mature:
    default: false
    type: bool

  isthereanydeal_minimum_price:
    default: 0
    type: float

  isthereanydeal_shops:
    default: "61|16|35"
    type: list
    list_type: compact
